num_context_points: null
run_gp_baseline: False
mcmc:
  num_warmup: 4000
  num_samples: 10000
  num_chains: 4
# priors names and args must be compat with Numpyro distributions
priors: 
  beta:
    numpyro_dist: Normal
  var:
    numpyro_dist: Dirichlet
    kwargs:
      concentration: [1.0]
  ls:
    numpyro_dist: Beta
    kwargs:
      concentration1: 3.0
      concentration0: 7.0
  period:
    numpyro_dist: HalfNormal