defaults:
  - _self_ # use default global values below
  - model: tnp_kr
seed: 42
wandb: True
project: Skin Lesions
train_num_steps: 10000
valid_num_steps: 1000
valid_interval: 2000
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 3.0
    - _target_: optax.yogi
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 2.0e-3
        decay_steps: ${train_num_steps}
        alpha: 2.0e-4
