cls: SPTx
kwargs:
  min_std: 0.05
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  dec:
    cls: KRStack
    kwargs:
      num_blks: 4
      num_reps: 2
      blk:
        cls: KRBlock
        kwargs:
          attn:
            cls: MultiheadFastAttention
            kwargs:
              num_ortho_features: 256
  head:
    cls: MLP
    kwargs:
      dims: [128, 2]
