data:
  iso: "MOZ"
  query: "YY==2007"
  res: 150 # this rounds data to the grid of res arc-seconds unless None
mcmc:
  seed: 42
  num_warmup: 1000
  num_samples: 1000
  num_chains: 4
  # can be parallel, sequential, vectorized (experimental), or vmap
  chain_method: "vectorized"
  progress_bar: True
  thinning: 10
prediction:
  seed: 42
  model: "gp"
  iso: "MOZ"
  region: "Gaza"
  batch_size: 4
  res: 150