mcmc:
  seed: 42
  num_warmup: 1000
  num_samples: 1000
  num_chains: 2
  # can be parallel, sequential, vectorized (experimental), or vmap
  chain_method: "vectorized"
  progress_bar: True
data:
  force_redownload: False
  iso: "MOZ"
  year: 2012

seed: 42
model: "gp"
batch_size: 4