seed: 42
mcmc: null # path to MCMC results, latest if null
np: "gp_pointwise" # gp, gp_pointwise or path to a neural process checkpoint path
# iso, region will be taken from the mcmc run if not defined. this is different than setting to null
# iso: "tza"
# region: null
batch_size: 16
res: 150
year: 2015 # required for loading urban/rural target covariates