defaults:
  - _self_ # use default global values below
  - data: tza
  - model: spatial/tnp_kr_scan 
  # specified in code
  # - kernel: rbf 
seed: 42
wandb: True
project: Disease Mapping
train_num_steps: 100000
valid_num_steps: 5000
valid_interval: 10000
plot_interval: 10000
# optimizer:
#   _target_: optax.chain
#   _args_:
#     - _target_: optax.clip_by_global_norm
#       max_norm: 3.0
#     - _target_: optax.yogi
#       learning_rate:
#         _target_: optax.cosine_decay_schedule
#         init_value: 1.0e-3
#         decay_steps: ${train_num_steps}
#         alpha: 1.0e-4
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adamw
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 1.0e-3
        decay_steps: ${train_num_steps}
        alpha: 2.0e-5
      b1: 0.9
      b2: 0.999
      weight_decay: 1.0e-4
input_format: "survey" # survey -> [n_pos, n], or theta -> [n_pos / n]