_target_: dl4bi.meta_learning.TNPKR
num_blks: 1
num_reps: 1
embed_all:
  _target_: dl4bi.mlp.MLP
  dims: [64]
blk:
  _target_: dl4bi.transformer.KRBlock
  attn:
    _target_: dl4bi.attention.MultiHeadAttention
    num_heads: 2
  ffn:
    _target_: dl4bi.core.utils.identity
    _partial_: true
head:
  _target_: dl4bi.mlp.MLP
  dims: [9]
output_fn:
  _target_: dl4bi.core.model_output.MultinomialOutput.from_activations
  _partial_: true
