data:
  grid:
    - start: 0.0
      stop: 1.0
      num: 128
  obs_noise: 0.1
  num_test: 32
  period: 0.2
  loader:
    batch_size: 16

infer:
  num_warmup: 500
  num_samples: 1000

train:
  num_batches: 1000

shared:
  embed_dim: 128
  dec_z_dims: ${eval:'[${.embed_dim} * n for n in [3, 2, 1]]'}
  dec_f_dims: ${eval:'[${.embed_dim} * n for n in [3, 2, 1]]+[1]'}
  post_process_dims: ${eval:'[${.embed_dim} * 2] * 4 + [${.embed_dim}]'}

model:
  cls: AttentiveNeuralProcess
  kwargs:
    embed_s:
      cls: LearnableEmbedding
      kwargs:
        map:
          func: 'lambda x: x'
          # cls: GaussianFourierEmbedding
          # kwargs:
          #   embed_dim: ${shared.embed_dim}
          #   input_dim: 1
          #   var: 10.0
        post_process:
          cls: MLP
          kwargs:
            dims: ${shared.post_process_dims}
    embed_s_f:
      cls: LearnableEmbedding
      kwargs:
        map:
          func: 'lambda x: x'
          # cls: GaussianFourierEmbedding
          # kwargs:
          #   embed_dim: ${shared.embed_dim}
          #   input_dim: 2
          #   var: 10.0
        post_process:
          cls: MLP
          kwargs:
            dims: ${shared.post_process_dims}
    enc_ctx_local:
      cls: TransformerEncoder
    enc_ctx_global:
      cls: TransformerEncoder
    cross_attn:
      cls: MultiheadAttention
    dec_z_mu:
      cls: MLP
      kwargs:
        dims: ${shared.dec_z_dims}
    dec_z_log_var:
      cls: MLP
      kwargs:
        dims: ${shared.dec_z_dims}
    dec_f_mu:
      cls: MLP
      kwargs:
        dims: ${shared.dec_f_dims}
    dec_f_log_var:
      cls: MLP
      kwargs:
        dims: ${shared.dec_f_dims}
