defaults:
  - _self_ # use default global values below
  - data: England
  - kernel: rbf_fixed
  - model: prior_cvae
  - infer: baseline
seed: 42
wandb: True
is_gp: True
project: UK_disease_distribution
batch_size: 1024