cls: TransformerVAE
kwargs:
  z_dim: 363
  encoder:
    cls: AttentionVAE
    kwargs:
      condition_bias: true
      feat_enc:
        cls: MLP
        kwargs:
          dims: [64, 64]
      blk:
        cls: TransformerEncoder
        kwargs:
          num_blks: 5
          blk:
            cls: TransformerEncoderBlock
            kwargs:
              ffn:
                cls: MLP
                kwargs:
                  dims: [64, 64]
      head_z_mu:
        cls: MLP
        kwargs:
          dims: [64, 32, 1]
      head_z_log_var:
        cls: MLP
        kwargs:
          dims: [64, 32, 1]
  decoder:
    cls: Conditional_MLP
    kwargs:
      mlp_model:
        cls: MLP
        kwargs:
          dims: [363, 363]