cls: TransformerVAE
kwargs:
  decoder_only: true
  z_dim: 363
  encoder: null
  decoder:
    cls: AttentionVAE
    kwargs:
      condition_bias: false
      feat_enc:
        cls: MLP
        kwargs:
          dims: [64, 64]
      head:
        cls: MLP
        kwargs:
          dims: [64, 32, 1]
      
